name: Build iOS App

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest
    name: Build iOS package
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies & Generate iOS Platform
        run: |
          npm install
          mkdir -p www
          echo "<!DOCTYPE html><html><body><h1>Simply Smile</h1></body></html>" > www/index.html
          rm -rf ios
          npx cap add ios --packagemanager CocoaPods
          npx cap sync ios

      - name: Install CocoaPods
        run: |
          cd ios/App
          pod install

      - name: Build iOS Simulator App (Test Build)
        run: |
          xcodebuild -workspace ios/App/App.xcworkspace \
                     -scheme App \
                     -sdk iphonesimulator \
                     -configuration Debug \
                     build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO

      - name: Upload iOS Simulator Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: App-Simulator-Debug
          path: ios/App/build/Debug-iphonesimulator/App.app
